name: Auto-Post WP
on:
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      WP_USER:        ${{ secrets.WP_USER }}
      WP_APP_PW:      ${{ secrets.WP_APP_PW }}

    steps:
      # ① コード取得
      - uses: actions/checkout@v4

      # ② デバッグ：環境変数が渡っているか確認
      - name: echo WP credentials prefix
        run: |
          echo "USER=${WP_USER}"
          echo "PW_PREFIX=${WP_APP_PW:0:8}"

      # ③ Python 3.11
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ④ 依存インストール
      - run: pip install -r requirements.txt

      # ⑤ 記事生成 → Draft
      - run: python generate.py

      # ⑥ パラフレーズ → refined
      - run: python refine.py

      # ⑦ refined があれば WordPress へ投稿
      - name: Post to WordPress if refined exists
        run: |
          FILE=$(ls refined_*.md 2>/dev/null || true)
          if [ -n "$FILE" ]; then
            python post_wp.py "$FILE"
          else
            echo "::warning ::No refined file to post"
          fi
