name: Auto-Post WP
on:
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      WP_USER:        ${{ secrets.WP_USER }}
      WP_APP_PW:      ${{ secrets.WP_APP_PW }}

    steps:
      # ① リポジトリをチェックアウト
      - uses: actions/checkout@v4

      # ▼▼▼ ここからデバッグ追加 ▼▼▼
      - name: echo WP credentials prefix         # ← 好きな名前で OK
        run: |
          echo "USER = ${WP_USER}"
          echo "PW_PREFIX = ${WP_APP_PW:0:8}"
      # ▲▲▲ ここまでデバッグ追加 ▲▲▲

      # ② Python セットアップ
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ③ 残りは従来どおり
      - run: pip install -r requirements.txt
      - run: python generate.py
      - run: python refine.py
      - name: Post to WordPress if refined exists
        run: |
          FILE=$(ls refined_*.md 2>/dev/null || true)
          if [ -n "$FILE" ]; then
            python post_wp.py "$FILE"
          else
            echo "::warning ::No refined file to post"
          fi
